//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTOS
    {
        public int Id { get; set; }
        public byte[] Imagem { get; set; }
        public int Receita_Id { get; set; }
    
        public virtual RECEITAS RECEITAS { get; set; }
    }
}
