//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENSPEDIDO
    {
        public int Id { get; set; }
        public short Quant { get; set; }
        public decimal ValorUnitario { get; set; }
        public int Linha_Id { get; set; }
        public int Pedido_Id { get; set; }
    
        public virtual PEDIDOS PEDIDOS { get; set; }
        public virtual LINHAS LINHAS { get; set; }
    }
}
