//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LINHAS()
        {
            this.ITENSPEDIDO = new HashSet<ITENSPEDIDO>();
            this.RECEITAS = new HashSet<RECEITAS>();
        }
    
        public int Id { get; set; }
        public string CodLinha { get; set; }
        public string DescricaoCor { get; set; }
        public int QtdFechada { get; set; }
        public int QtdAberta { get; set; }
        public int TipoLinha_Id { get; set; }
        public int Fabricante_Id { get; set; }
    
        public virtual FABRICANTES FABRICANTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSPEDIDO> ITENSPEDIDO { get; set; }
        public virtual TIPOSLINHA TIPOSLINHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEITAS> RECEITAS { get; set; }
    }
}
