//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAmigContext : DbContext
    {
        public DBAmigContext()
            : base("name=DBAmigContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FABRICANTES> FABRICANTES { get; set; }
        public virtual DbSet<FOTOS> FOTOS { get; set; }
        public virtual DbSet<ITENSPEDIDO> ITENSPEDIDO { get; set; }
        public virtual DbSet<LINHAS> LINHAS { get; set; }
        public virtual DbSet<PEDIDOS> PEDIDOS { get; set; }
        public virtual DbSet<RECEITAS> RECEITAS { get; set; }
        public virtual DbSet<REVISTAS> REVISTAS { get; set; }
        public virtual DbSet<TIPOSLINHA> TIPOSLINHA { get; set; }
    }
}
