//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEITAS()
        {
            this.FOTOS = new HashSet<FOTOS>();
            this.LINHAS = new HashSet<LINHAS>();
        }
    
        public int Id { get; set; }
        public string None { get; set; }
        public string Descricao { get; set; }
        public int Revista_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTOS> FOTOS { get; set; }
        public virtual REVISTAS REVISTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINHAS> LINHAS { get; set; }
    }
}
