//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFAmig
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVISTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REVISTAS()
        {
            this.RECEITAS = new HashSet<RECEITAS>();
        }
    
        public int Id { get; set; }
        public string Tema { get; set; }
        public short NumeroEdicao { get; set; }
        public byte[] FotoCapa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEITAS> RECEITAS { get; set; }
    }
}
