USE [C:\Users\jbgal\source\repos\DBFAmig\App_Data\DBAMIG.MDF]
GO
/****** Object:  Table [dbo].[FABRICANTES]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FABRICANTES](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_FABRICANTES] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FOTOS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FOTOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Imagem] [varbinary](max) NOT NULL,
	[Receita_Id] [int] NOT NULL,
 CONSTRAINT [PK_FOTOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ITENSPEDIDO]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITENSPEDIDO](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Quant] [smallint] NOT NULL,
	[ValorUnitario] [decimal](18, 0) NOT NULL,
	[Linha_Id] [int] NOT NULL,
	[Pedido_Id] [int] NOT NULL,
 CONSTRAINT [PK_ITENSPEDIDO] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LINHAS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LINHAS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CodLinha] [nvarchar](max) NOT NULL,
	[DescricaoCor] [nvarchar](255) NOT NULL,
	[QtdFechada] [int] NOT NULL,
	[QtdAberta] [int] NOT NULL,
	[TipoLinha_Id] [int] NOT NULL,
	[Fabricante_Id] [int] NOT NULL,
 CONSTRAINT [PK_LINHAS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PEDIDOS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDOS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Data] [datetime] NOT NULL,
 CONSTRAINT [PK_PEDIDOS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECEITAS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEITAS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[None] [nvarchar](255) NOT NULL,
	[Descricao] [nvarchar](4000) NOT NULL,
	[Revista_Id] [int] NOT NULL,
 CONSTRAINT [PK_RECEITAS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECEITASLINHAS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEITASLINHAS](
	[Receita_Id] [int] NOT NULL,
	[Linha_Id] [int] NOT NULL,
 CONSTRAINT [PK_RECEITASLINHAS] PRIMARY KEY CLUSTERED 
(
	[Receita_Id] ASC,
	[Linha_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REVISTAS]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REVISTAS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Tema] [nvarchar](128) NOT NULL,
	[NumeroEdicao] [smallint] NOT NULL,
	[FotoCapa] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_REVISTAS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPOSLINHA]    Script Date: 07/09/2020 12:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPOSLINHA](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_TIPOSLINHA] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[FOTOS]  WITH CHECK ADD  CONSTRAINT [FK_ReceitaFoto] FOREIGN KEY([Receita_Id])
REFERENCES [dbo].[RECEITAS] ([Id])
GO
ALTER TABLE [dbo].[FOTOS] CHECK CONSTRAINT [FK_ReceitaFoto]
GO
ALTER TABLE [dbo].[ITENSPEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_CompraItens] FOREIGN KEY([Pedido_Id])
REFERENCES [dbo].[PEDIDOS] ([Id])
GO
ALTER TABLE [dbo].[ITENSPEDIDO] CHECK CONSTRAINT [FK_CompraItens]
GO
ALTER TABLE [dbo].[ITENSPEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_LinhaItens] FOREIGN KEY([Linha_Id])
REFERENCES [dbo].[LINHAS] ([Id])
GO
ALTER TABLE [dbo].[ITENSPEDIDO] CHECK CONSTRAINT [FK_LinhaItens]
GO
ALTER TABLE [dbo].[LINHAS]  WITH CHECK ADD  CONSTRAINT [FK_FabricanteLinha] FOREIGN KEY([Fabricante_Id])
REFERENCES [dbo].[FABRICANTES] ([Id])
GO
ALTER TABLE [dbo].[LINHAS] CHECK CONSTRAINT [FK_FabricanteLinha]
GO
ALTER TABLE [dbo].[LINHAS]  WITH CHECK ADD  CONSTRAINT [FK_TipoLinhaLinha] FOREIGN KEY([TipoLinha_Id])
REFERENCES [dbo].[TIPOSLINHA] ([Id])
GO
ALTER TABLE [dbo].[LINHAS] CHECK CONSTRAINT [FK_TipoLinhaLinha]
GO
ALTER TABLE [dbo].[RECEITAS]  WITH CHECK ADD  CONSTRAINT [FK_RevistaReceita] FOREIGN KEY([Revista_Id])
REFERENCES [dbo].[REVISTAS] ([Id])
GO
ALTER TABLE [dbo].[RECEITAS] CHECK CONSTRAINT [FK_RevistaReceita]
GO
ALTER TABLE [dbo].[RECEITASLINHAS]  WITH CHECK ADD  CONSTRAINT [FK_RECEITASLINHAS_Linha] FOREIGN KEY([Linha_Id])
REFERENCES [dbo].[LINHAS] ([Id])
GO
ALTER TABLE [dbo].[RECEITASLINHAS] CHECK CONSTRAINT [FK_RECEITASLINHAS_Linha]
GO
ALTER TABLE [dbo].[RECEITASLINHAS]  WITH CHECK ADD  CONSTRAINT [FK_RECEITASLINHAS_Receita] FOREIGN KEY([Receita_Id])
REFERENCES [dbo].[RECEITAS] ([Id])
GO
ALTER TABLE [dbo].[RECEITASLINHAS] CHECK CONSTRAINT [FK_RECEITASLINHAS_Receita]
GO
